version: '3.8'

services:
  # budgeter:
  #   build: .
  #   ports:
  #    - "8000:4566"
  #   depends_on:
  #     - db
  #     - localstack
  #   environment:
  #     - MYSQL_USER=dev
  #     - MYSQL_PASSWORD=none
  #   entrypoint:
  #     - bash
  #     - -c
  #     - |
  #       set -e
  #       echo '################################################'
  #       echo 'Waiting for MySQL and localstack to be available'
  #       export MYSQL_USER="$$MYSQL_USER"
  #       export MYSQL_PASSWORD="$$MYSQL_PASSWORD"
  #       maxTries=10
  #       while [ "$$maxTries" -gt 0 ] && ! mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --silent --execute "SELECT 1;" do
  #         sleep 1
  #       done
  #       echo
  #       if [ "$$maxTries -le 0"]; then
  #         echo >&2 'error: unable to conect to MySQL after 10 tries'
  #         exit 1
  #       fi
  #   container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
  # localstack:
  #   image: localstack/localstack:latest
  #   ports:
  #     - "127.0.0.1:4566:4566"            # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559"  # external services port range
  #     - "127.0.0.1:53:53"                # DNS config (only required for Pro)
  #     - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
  #     - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
  #   environment:
  #     - DEBUG=${DEBUG-}
  #     - PERSISTENCE=${PERSISTENCE-}
  #     - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
  #     - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #   volumes:
  #     - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  db:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "31000:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: budgetdb
    # healthcheck:
    #   test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5   

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
